name: Steps Examples
on:
  workflow_dispatch:

jobs:
    steps-examples:
      runs-on: ubuntu-latest
      steps: 
        - run: mkdir ~/testmachine
        - run: uname -a > ~/testmachine/output.txt
        - run: cat ~/testmachine/output.txt
        - run: ls -alhR
        
        
