name: Uses Examples

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
         python-version: '3.13'
         
      - name: Python script
        run: python my_script.py
         


      

  
